apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kafka-external
  labels:
    app: kafka
spec:
  type: NodePort
  ports:
    - name: external
      port: 9094
      targetPort: 9094
      nodePort: 30092
  selector:
    strimzi.io/name: my-cluster-kafka
