apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaledobject
  labels:
    deploymentName: quarkus-eda-demo
spec:
  scaleTargetRef:
    name: quarkus-eda-demo
  pollingInterval: 30
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: my-cluster-kafka-bootstrap.kafka-keda.svc:9092
        consumerGroup: my-group
        topic: my-topic
        lagThreshold: "50"
        offsetResetPolicy: latest
